spring.application.name=demo

server.port=7070

server.servlet.context-path=/mycoolapp

management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=info
management.info.env.enabled=true

info.app.name=My cool app
info.app.description=A crazy app
info.app.version=1.0.0

coach.name=Micky Mouse
team.name=The Mouse Club